In [1]:
# Data Handling
import pandas as pd
import numpy as np

# Encoding
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

# Feature Scaling
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

# Train Test Split
from sklearn.model_selection import train_test_split

# Column Transformer
from sklearn.compose import ColumnTransformer

# Pipeline
from sklearn.pipeline import Pipeline

In [2]:
data = pd.read_excel("../dataset/cleaned_output.xlsx")

In [12]:
le = LabelEncoder()

data["Country_Label"] = le.fit_transform(data["Country"])

print(data[["Country", "Country_Label"]].head())

          Country  Country_Label
0  United Kingdom             35
1  United Kingdom             35
2  United Kingdom             35
3  United Kingdom             35
4  United Kingdom             35

In [13]:
country_encoded = pd.get_dummies(
    data["Country"],
    prefix="Country"
)

data = pd.concat(
    [data, country_encoded],
    axis=1
)

data.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Country_Label,Country_Australia,...,Country_RSA,Country_Saudi Arabia,Country_Singapore,Country_Spain,Country_Sweden,Country_Switzerland,Country_USA,Country_United Arab Emirates,Country_United Kingdom,Country_Unspecified
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,35,False,...,False,False,False,False,False,False,False,False,True,False
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,35,False,...,False,False,False,False,False,False,False,False,True,False
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,35,False,...,False,False,False,False,False,False,False,False,True,False
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,35,False,...,False,False,False,False,False,False,False,False,True,False
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,35,False,...,False,False,False,False,False,False,False,False,True,False

In [14]:
data["Revenue"] = data["Quantity"] * data["UnitPrice"]

In [15]:
features_to_scale = [
    "Quantity",
    "UnitPrice",
    "Revenue",
    "Country_Label"
]

In [16]:
scaler = StandardScaler()

data[features_to_scale] = scaler.fit_transform(
    data[features_to_scale]
)

data.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Country_Label,Country_Australia,...,Country_Saudi Arabia,Country_Singapore,Country_Spain,Country_Sweden,Country_Switzerland,Country_USA,Country_United Arab Emirates,Country_United Kingdom,Country_Unspecified,Revenue
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,-0.024705,2010-12-01 08:26:00,-0.013246,17850,United Kingdom,0.324377,False,...,False,False,False,False,False,False,False,True,False,-0.012347
1,536365,71053,WHITE METAL LANTERN,-0.024705,2010-12-01 08:26:00,-0.001205,17850,United Kingdom,0.324377,False,...,False,False,False,False,False,False,False,True,False,-0.000636
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,-0.016714,2010-12-01 08:26:00,-0.010379,17850,United Kingdom,0.324377,False,...,False,False,False,False,False,False,False,True,False,0.003221
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,-0.024705,2010-12-01 08:26:00,-0.001205,17850,United Kingdom,0.324377,False,...,False,False,False,False,False,False,False,True,False,-0.000636
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,-0.024705,2010-12-01 08:26:00,-0.001205,17850,United Kingdom,0.324377,False,...,False,False,False,False,False,False,False,True,False,-0.000636

In [17]:
scaler = MinMaxScaler()

data[features_to_scale] = scaler.fit_transform(
    data[features_to_scale]
)

In [18]:
X = data[features_to_scale]

print(X.head())

   Quantity  UnitPrice   Revenue  Country_Label
0  0.500037   0.000065  0.500045       0.972222
1  0.500037   0.000087  0.500060       0.972222
2  0.500049   0.000071  0.500065       0.972222
3  0.500037   0.000087  0.500060       0.972222
4  0.500037   0.000087  0.500060       0.972222

In [19]:
X_train, X_test = train_test_split(
    X,
    test_size=0.20,
    random_state=42
)

print("Training Shape :", X_train.shape)
print("Testing Shape  :", X_test.shape)

Training Shape : (321283, 4)
Testing Shape  : (80321, 4)

In [20]:
print(data.shape)
print(data.columns)

(401604, 158)
Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country', 'Country_Label',
       'Country_Australia',
       ...
       'Country_Saudi Arabia', 'Country_Singapore', 'Country_Spain',
       'Country_Sweden', 'Country_Switzerland', 'Country_USA',
       'Country_United Arab Emirates', 'Country_United Kingdom',
       'Country_Unspecified', 'Revenue'],
      dtype='str', length=158)

In [21]:
X_train.to_csv("../dataset/X_train.csv", index=False)
X_test.to_csv("../dataset/X_test.csv", index=False)